import React, { createContext, useContext, useMemo, useState } from 'react';
import type { Locale } from '../api/types';

const dictionaries = {
  tr: {
    home:'Ana Sayfa', search:'Keşfet', create:'Paylaş', favorites:'Favoriler', profile:'Profil',
    wordmark:'Home App', feedTitle:'Gerçek mağazalar, gerçek deneyimler', feedIntro:'İnsanların ev ve yaşam mağazalarında neler keşfettiğine göz at.',
    verified:'Doğrulanmış ziyaret', save:'Kaydet', saved:'Kaydedildi', comments:'yorum', likes:'beğeni',
    searchTitle:'Gitmeye değer mağazaları bul', searchHint:"Kadıköy'de modern avize mağazaları", recent:'Son aramalar', categories:'Ev kategorileri', nearby:'Yakınımda keşfet',
    results:'sonuç', noCommunity:'Henüz topluluk yorumu yok', firstReview:'İlk deneyimi sen paylaş.', homeAppRating:'Home App', googleRating:'Google', reviews:'yorum', away:'uzakta',
    storeQuestion:'Gitmeye değer mi?', directions:'Yol tarifi', review:'Yorum yaz', share:'Paylaş', photos:'Fotoğraflar', about:'Mağaza hakkında', community:'Topluluk deneyimleri', external:'Dış kaynak',
    signInTitle:'Devam etmek için giriş yap', signInBody:'Kaydettiğin mağazaları ve paylaşımlarını tüm cihazlarında gör.', google:'Google ile devam et', email:'E-posta ile devam et', later:'Şimdi değil',
    emailTitle:'E-posta adresin', emailBody:'Sana tek kullanımlık 6 haneli bir kod göndereceğiz.', sendCode:'Kodu gönder', codeTitle:'Kodu gir', verify:'Doğrula ve devam et',
    createTitle:'Ziyaretini paylaş', selectStore:'Mağaza seç', locationStep:'Konumu doğrula', ratingStep:'Puan ver', photosStep:'Fotoğraf ekle', experienceStep:'Deneyimini anlat', publish:'Yayınla', locationWhy:'Bu yorumu mağazayı gerçekten ziyaret edenlerin yazdığını göstermek için konumunu yalnızca bu adımda kullanıyoruz.', allowLocation:'Konumu doğrula',
    favoritesTitle:'Gitmek istediğin yerler', favoritesEmpty:'Kaydettiğin mağazalar burada görünecek.', profileTitle:'Senin Home App’in', profileBody:'Yorumlarını yönetmek ve tercihlerini görmek için giriş yap.', settings:'Ayarlar', language:'Dil', authRequired:'Bu işlem hesabına kaydedilir.', close:'Kapat', popular:'Popüler', lighting:'Aydınlatma', furniture:'Mobilya', textile:'Ev tekstili', decoration:'Dekorasyon', retry:'Tekrar dene', searchAction:'Ara', zeroTitle:'Tam eşleşme bulamadık', zeroBody:'Arama alanını genişletmeyi veya daha genel bir ürün adı denemeyi dene.',
  },
  en: {
    home:'Home', search:'Discover', create:'Create', favorites:'Favorites', profile:'Profile', wordmark:'Home App', feedTitle:'Real stores, real experiences', feedIntro:'See what people discovered inside home and living stores.', verified:'Verified visit', save:'Save', saved:'Saved', comments:'comments', likes:'likes', searchTitle:'Find stores worth the trip', searchHint:'Affordable curtain stores near me', recent:'Recent searches', categories:'Home categories', nearby:'Discover nearby', results:'results', noCommunity:'No community reviews yet', firstReview:'Be the first to share your experience.', homeAppRating:'Home App', googleRating:'Google', reviews:'reviews', away:'away', storeQuestion:'Is it worth the trip?', directions:'Directions', review:'Review', share:'Share', photos:'Photos', about:'About this store', community:'Community experiences', external:'External source', signInTitle:'Sign in to continue', signInBody:'Keep saved stores and contributions with you across devices.', google:'Continue with Google', email:'Continue with Email', later:'Not now', emailTitle:'Your email address', emailBody:'We’ll send you a single-use 6-digit code.', sendCode:'Send code', codeTitle:'Enter your code', verify:'Verify and continue', createTitle:'Share your visit', selectStore:'Select store', locationStep:'Verify location', ratingStep:'Add rating', photosStep:'Add photos', experienceStep:'Tell your experience', publish:'Publish', locationWhy:'We only use your location at this step to show that this review came from someone who visited the store.', allowLocation:'Verify location', favoritesTitle:'Places you want to visit', favoritesEmpty:'Stores you save will appear here.', profileTitle:'Your Home App', profileBody:'Sign in to manage your reviews and preferences.', settings:'Settings', language:'Language', authRequired:'This action is saved to your account.', close:'Close', popular:'Popular', lighting:'Lighting', furniture:'Furniture', textile:'Home textile', decoration:'Decoration', retry:'Try again', searchAction:'Search', zeroTitle:'No close matches yet', zeroBody:'Try widening the area or using a broader product name.',
  },
  de: {
    home:'Start', search:'Entdecken', create:'Beitrag', favorites:'Favoriten', profile:'Profil', wordmark:'Home App', feedTitle:'Echte Geschäfte, echte Erfahrungen', feedIntro:'Entdecke, was Menschen in Wohn- und Einrichtungsgeschäften gefunden haben.', verified:'Verifizierter Besuch', save:'Speichern', saved:'Gespeichert', comments:'Kommentare', likes:'Gefällt mir', searchTitle:'Finde Geschäfte, die den Weg wert sind', searchHint:'günstige Möbelgeschäfte in Berlin', recent:'Letzte Suchen', categories:'Wohnkategorien', nearby:'In der Nähe entdecken', results:'Ergebnisse', noCommunity:'Noch keine Community-Bewertungen', firstReview:'Teile als Erste:r deine Erfahrung.', homeAppRating:'Home App', googleRating:'Google', reviews:'Bewertungen', away:'entfernt', storeQuestion:'Lohnt sich der Weg?', directions:'Route', review:'Bewerten', share:'Teilen', photos:'Fotos', about:'Über dieses Geschäft', community:'Erfahrungen der Community', external:'Externe Quelle', signInTitle:'Zum Fortfahren anmelden', signInBody:'Behalte gespeicherte Geschäfte und Beiträge auf allen Geräten.', google:'Weiter mit Google', email:'Weiter mit E-Mail', later:'Nicht jetzt', emailTitle:'Deine E-Mail-Adresse', emailBody:'Wir senden dir einen einmaligen 6-stelligen Code.', sendCode:'Code senden', codeTitle:'Code eingeben', verify:'Bestätigen und weiter', createTitle:'Teile deinen Besuch', selectStore:'Geschäft auswählen', locationStep:'Standort bestätigen', ratingStep:'Bewertung hinzufügen', photosStep:'Fotos hinzufügen', experienceStep:'Erfahrung beschreiben', publish:'Veröffentlichen', locationWhy:'Wir verwenden deinen Standort nur in diesem Schritt, um zu zeigen, dass die Bewertung von einem echten Besuch stammt.', allowLocation:'Standort bestätigen', favoritesTitle:'Orte, die du besuchen möchtest', favoritesEmpty:'Gespeicherte Geschäfte erscheinen hier.', profileTitle:'Dein Home App', profileBody:'Melde dich an, um Bewertungen und Einstellungen zu verwalten.', settings:'Einstellungen', language:'Sprache', authRequired:'Diese Aktion wird in deinem Konto gespeichert.', close:'Schließen', popular:'Beliebt', lighting:'Beleuchtung', furniture:'Möbel', textile:'Heimtextilien', decoration:'Dekoration', retry:'Erneut versuchen', searchAction:'Suchen', zeroTitle:'Noch keine passenden Treffer', zeroBody:'Vergrößere den Suchbereich oder verwende einen allgemeineren Produktnamen.',
  },
  ru: {
    home:'Главная', search:'Поиск', create:'Создать', favorites:'Избранное', profile:'Профиль', wordmark:'Home App', feedTitle:'Настоящие магазины, реальные впечатления', feedIntro:'Узнайте, что люди находят в магазинах товаров для дома.', verified:'Подтверждённое посещение', save:'Сохранить', saved:'Сохранено', comments:'комментарии', likes:'отметки', searchTitle:'Найдите магазины, куда стоит поехать', searchHint:'где купить шторы в Анталии', recent:'Недавние запросы', categories:'Категории для дома', nearby:'Искать рядом', results:'результатов', noCommunity:'Пока нет отзывов сообщества', firstReview:'Поделитесь первым впечатлением.', homeAppRating:'Home App', googleRating:'Google', reviews:'отзывов', away:'от вас', storeQuestion:'Стоит ли ехать?', directions:'Маршрут', review:'Отзыв', share:'Поделиться', photos:'Фото', about:'О магазине', community:'Отзывы сообщества', external:'Внешний источник', signInTitle:'Войдите, чтобы продолжить', signInBody:'Сохранённые магазины и публикации будут доступны на всех устройствах.', google:'Продолжить с Google', email:'Продолжить с эл. почтой', later:'Не сейчас', emailTitle:'Ваш адрес эл. почты', emailBody:'Мы отправим одноразовый 6-значный код.', sendCode:'Отправить код', codeTitle:'Введите код', verify:'Подтвердить', createTitle:'Расскажите о посещении', selectStore:'Выберите магазин', locationStep:'Подтвердите место', ratingStep:'Поставьте оценку', photosStep:'Добавьте фото', experienceStep:'Опишите впечатления', publish:'Опубликовать', locationWhy:'Мы используем геопозицию только на этом шаге, чтобы подтвердить реальное посещение магазина.', allowLocation:'Подтвердить место', favoritesTitle:'Места, которые хочется посетить', favoritesEmpty:'Сохранённые магазины появятся здесь.', profileTitle:'Ваш Home App', profileBody:'Войдите, чтобы управлять отзывами и настройками.', settings:'Настройки', language:'Язык', authRequired:'Это действие сохраняется в аккаунте.', close:'Закрыть', popular:'Популярное', lighting:'Освещение', furniture:'Мебель', textile:'Домашний текстиль', decoration:'Декор', retry:'Повторить', searchAction:'Найти', zeroTitle:'Точных совпадений пока нет', zeroBody:'Увеличьте область поиска или используйте более общее название товара.',
  },
} as const;

type TranslationKey = keyof typeof dictionaries.en;
type I18n = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: TranslationKey) => string };
const I18nContext = createContext<I18n | null>(null);

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>('tr');
  const value = useMemo(() => ({ locale, setLocale, t: (key: TranslationKey) => dictionaries[locale][key] }), [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error('I18nProvider missing'); return value; }
export const localeNames: Record<Locale, string> = { tr: 'Türkçe', en: 'English', de: 'Deutsch', ru: 'Русский' };

