import React, { useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, StyleSheet, Text, TextInput, View } from 'react-native';
import { PrimaryButton } from '../components/Primitives';
import { useI18n } from '../i18n';
import { colors, radius, spacing } from '../theme/tokens';

export function EmailAuth({visible,onClose}:{visible:boolean;onClose:()=>void}) { const {t}=useI18n(); const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [sent,setSent]=useState(false); return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={styles.screen}><View style={styles.pad}><Text style={styles.kicker}>{t('wordmark')}</Text><Text style={styles.title}>{sent?t('codeTitle'):t('emailTitle')}</Text><Text style={styles.body}>{sent?email:t('emailBody')}</Text><TextInput accessibilityLabel={sent?t('codeTitle'):t('emailTitle')} value={sent?code:email} onChangeText={sent?setCode:setEmail} autoCapitalize="none" keyboardType={sent?'number-pad':'email-address'} maxLength={sent?6:254} style={styles.input} placeholder={sent?'000000':'name@example.com'} placeholderTextColor={colors.inkMuted}/><PrimaryButton label={sent?t('verify'):t('sendCode')} disabled={sent?code.length!==6:!email.includes('@')} onPress={()=>sent?onClose():setSent(true)}/><PrimaryButton label={t('close')} kind="quiet" onPress={onClose}/></View></KeyboardAvoidingView></Modal> }
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas,justifyContent:'center'},pad:{padding:spacing.xxl},kicker:{fontSize:13,textTransform:'uppercase',letterSpacing:1.7,color:colors.accent,fontWeight:'800'},title:{fontSize:32,lineHeight:38,fontWeight:'700',color:colors.ink,marginTop:spacing.md},body:{fontSize:16,lineHeight:24,color:colors.inkMuted,marginTop:spacing.sm},input:{marginTop:spacing.xxl,minHeight:56,borderWidth:1,borderColor:colors.line,borderRadius:radius.control,backgroundColor:colors.surface,paddingHorizontal:spacing.lg,fontSize:18,color:colors.ink}});

