import React, { useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, StyleSheet, Text, TextInput, View } from 'react-native';
import { mobileApi, clearSession, saveSession } from '../api/client';
import { PrimaryButton } from '../components/Primitives';
import { useI18n } from '../i18n';
import { colors, radius, spacing } from '../theme/tokens';

export function EmailAuth({visible,onClose,onAuthenticated}:{visible:boolean;onClose:()=>void;onAuthenticated:()=>void}) {
  const {t,locale}=useI18n(); const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [sent,setSent]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const submit=async()=>{setBusy(true);setError('');try{if(!sent){await mobileApi.requestCode(email.trim(),locale);setSent(true);return;}const pair=await mobileApi.verifyCode(email.trim(),code,locale);await saveSession(pair);onAuthenticated();onClose();}catch(reason){const codeValue=(reason as {error?:{code?:string}})?.error?.code;if(codeValue==='ACCOUNT_UNAVAILABLE'){await clearSession();setError(t('accountUnavailable'));}else setError((reason as {error?:{message?:string}})?.error?.message??t('authFailed'));}finally{setBusy(false);}};
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={styles.screen}><View style={styles.pad}><Text style={styles.kicker}>{t('wordmark')}</Text><Text style={styles.title}>{sent?t('codeTitle'):t('emailTitle')}</Text><Text style={styles.body}>{sent?email:t('emailBody')}</Text><TextInput accessibilityLabel={sent?t('codeTitle'):t('emailTitle')} value={sent?code:email} onChangeText={sent?value=>setCode(value.replace(/\D/g,'').slice(0,6)):setEmail} autoCapitalize="none" keyboardType={sent?'number-pad':'email-address'} maxLength={sent?6:254} style={styles.input} placeholder={sent?'000000':'name@example.com'} placeholderTextColor={colors.inkMuted}/>{!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<PrimaryButton label={sent?t('verify'):t('sendCode')} disabled={busy||(sent?code.length!==6:!email.includes('@'))} onPress={()=>void submit()}/><PrimaryButton label={t('close')} kind="quiet" onPress={onClose}/></View></KeyboardAvoidingView></Modal>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas,justifyContent:'center'},pad:{padding:spacing.xxl},kicker:{fontSize:13,textTransform:'uppercase',letterSpacing:1.7,color:colors.clay,fontWeight:'800'},title:{fontSize:32,lineHeight:38,fontWeight:'700',color:colors.ink,marginTop:spacing.md},body:{fontSize:16,lineHeight:24,color:colors.inkMuted,marginTop:spacing.sm},input:{marginTop:spacing.xxl,minHeight:56,borderWidth:1,borderColor:colors.line,borderRadius:radius.control,backgroundColor:colors.surface,paddingHorizontal:spacing.lg,fontSize:18,color:colors.ink},error:{color:'#9c332b',fontSize:14,lineHeight:20,marginTop:spacing.md}});
