import React, { useState } from 'react';
import { FlatList, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { SearchResult } from '../api/types';
import { imagery, searchFixture } from '../data/fixtures';
import { useI18n } from '../i18n';
import { colors, radius, spacing } from '../theme/tokens';
import { Icon } from '../components/Icon';
import { Rating, SearchField } from '../components/Primitives';

function ResultRow({item,index,onOpen}:{item:SearchResult;index:number;onOpen:(item:SearchResult)=>void}) { const {t,locale}=useI18n(); const km=((item.distance_meters??0)/1000).toLocaleString(locale,{maximumFractionDigits:1}); return <Pressable onPress={()=>onOpen(item)} style={({pressed})=>[styles.result,pressed&&{opacity:.7}]}><Image source={index===0?imagery.store:imagery.lighting} style={styles.thumb}/><View style={styles.resultBody}><Text style={styles.resultName}>{item.name}</Text><Text style={styles.address} numberOfLines={2}>{item.address}</Text><Text style={styles.distance}>{km} km {t('away')}</Text>{item.platform?<View style={styles.scores}><View><Text style={styles.source}>{t('homeAppRating')}</Text><View style={styles.inline}><Rating value={item.platform.average_rating}/><Text style={styles.count}>· {item.platform.review_count} {t('reviews')}</Text></View></View>{item.google&&<View><Text style={styles.source}>{t('googleRating')}</Text><View style={styles.inline}><Rating value={item.google.rating}/><Text style={styles.count}>· {item.google.rating_count}</Text></View></View>}</View>:<View style={styles.googleOnly}><Text style={styles.noCommunity}>{t('noCommunity')}</Text><View style={styles.inline}><Text style={styles.source}>{t('googleRating')}</Text><Rating value={item.google?.rating??0}/><Text style={styles.count}>· {item.google?.rating_count}</Text></View></View>}</View></Pressable>; }

export function SearchScreen({onOpen,onAuth}:{onOpen:(item:SearchResult)=>void;onAuth:()=>void}) { const {t}=useI18n(); const [query,setQuery]=useState(''); const [searched,setSearched]=useState(false); const submit=()=>setSearched(true); const chips=[t('lighting'),'chandelier','modern','Kadıköy'];
  if (searched) return <FlatList style={styles.screen} contentContainerStyle={styles.resultsContent} data={searchFixture.results} keyExtractor={i=>i.search_result_impression_id} ListHeaderComponent={<View style={styles.resultsHead}><SearchField value={query} onChange={setQuery} onSubmit={submit} placeholder={t('searchHint')}/><ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.chips}>{chips.map(c=><View style={styles.chip} key={c}><Text style={styles.chipText}>{c}</Text><Icon name="close" size={14}/></View>)}</ScrollView><Text style={styles.resultCount}>{searchFixture.results.length} {t('results')}</Text></View>} renderItem={({item,index})=><ResultRow item={item} index={index} onOpen={item=>item.id?onOpen(item):onAuth()}/>} />;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.landing} keyboardShouldPersistTaps="handled"><Text style={styles.kicker}>{t('search')}</Text><Text style={styles.title}>{t('searchTitle')}</Text><View style={{marginTop:spacing.xxl}}><SearchField value={query} onChange={setQuery} onSubmit={submit} placeholder={t('searchHint')}/></View><Text style={styles.section}>{t('recent')}</Text><Pressable onPress={()=>{setQuery("Kadıköy'de modern avize mağazaları");setSearched(true)}} style={styles.recent}><Icon name="search"/><Text style={styles.recentText}>Kadıköy’de modern avize mağazaları</Text></Pressable><Text style={styles.section}>{t('categories')}</Text><View style={styles.categoryGrid}>{[['lighting',t('lighting')],['furniture',t('furniture')],['textile',t('textile')],['decoration',t('decoration')]].map(([key,label])=><Pressable key={key} style={styles.category} onPress={()=>{setQuery(label);setSearched(true)}}><View style={styles.categoryMark}/><Text style={styles.categoryText}>{label}</Text></Pressable>)}</View><Pressable style={styles.nearby} onPress={()=>{setQuery(t('nearby'));setSearched(true)}}><Icon name="pin" color={colors.surface}/><Text style={styles.nearbyText}>{t('nearby')}</Text></Pressable></ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas},landing:{padding:spacing.lg,paddingBottom:120},resultsContent:{paddingBottom:112},kicker:{fontSize:14,textTransform:'uppercase',letterSpacing:1.7,color:colors.accent,fontWeight:'800',marginTop:spacing.lg},title:{fontSize:34,lineHeight:40,fontWeight:'700',color:colors.ink,marginTop:spacing.md,maxWidth:350},section:{fontSize:14,fontWeight:'700',color:colors.ink,marginTop:spacing.xxxl,marginBottom:spacing.md},recent:{flexDirection:'row',alignItems:'center',gap:spacing.md,minHeight:48,borderBottomWidth:1,borderColor:colors.line},recentText:{fontSize:15,color:colors.ink,flex:1},categoryGrid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.md},category:{width:'47%',backgroundColor:colors.surface,padding:spacing.lg,minHeight:88,justifyContent:'space-between',borderRadius:radius.media},categoryMark:{width:24,height:2,backgroundColor:colors.accent},categoryText:{fontSize:16,fontWeight:'700',color:colors.ink},nearby:{marginTop:spacing.xxxl,backgroundColor:colors.accent,padding:spacing.lg,minHeight:56,borderRadius:radius.control,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.sm},nearbyText:{fontSize:16,color:colors.surface,fontWeight:'700'},resultsHead:{padding:spacing.lg,paddingBottom:spacing.sm},chips:{marginTop:spacing.lg},chip:{backgroundColor:colors.muted,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.sm,marginRight:spacing.sm,flexDirection:'row',alignItems:'center',gap:spacing.sm},chipText:{fontSize:13,color:colors.ink},resultCount:{fontSize:13,color:colors.inkMuted,marginTop:spacing.xl},result:{flexDirection:'row',gap:spacing.lg,padding:spacing.lg,borderBottomWidth:1,borderColor:colors.line},thumb:{width:112,height:142,borderRadius:radius.media,resizeMode:'cover',backgroundColor:colors.muted},resultBody:{flex:1},resultName:{fontSize:19,lineHeight:24,fontWeight:'700',color:colors.ink},address:{fontSize:13,lineHeight:18,color:colors.inkMuted,marginTop:spacing.xs},distance:{fontSize:12,color:colors.accent,fontWeight:'700',marginTop:spacing.sm},scores:{marginTop:spacing.md,flexDirection:'row',gap:spacing.xl},source:{fontSize:11,textTransform:'uppercase',letterSpacing:.5,color:colors.inkMuted,fontWeight:'700'},inline:{flexDirection:'row',alignItems:'center',gap:4,marginTop:2},count:{fontSize:12,color:colors.inkMuted},googleOnly:{marginTop:spacing.md},noCommunity:{fontSize:13,lineHeight:18,color:colors.ink,fontWeight:'600',marginBottom:spacing.sm}});
