import React, { useState } from 'react';
import * as Location from 'expo-location';
import * as ImagePicker from 'expo-image-picker';
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { PrimaryButton } from '../components/Primitives';
import { useI18n, localeNames } from '../i18n';
import { colors, radius, spacing } from '../theme/tokens';
import type { Locale } from '../api/types';
import { mobileApi } from '../api/client';

const prototypeStoreId='4ea6429b-81b8-4a64-a8cd-1d5b045bf3b2';
export function CreateScreen({onAuth}:{onAuth:()=>void}) {
  const {t,locale}=useI18n(); const [step,setStep]=useState(0); const [rating,setRating]=useState(0); const [text,setText]=useState(''); const [proofId,setProofId]=useState<string>(); const [busy,setBusy]=useState(false); const steps=[t('selectStore'),t('locationStep'),t('ratingStep'),t('photosStep'),t('experienceStep')];
  const next=async()=>{if(step===0){onAuth();setStep(1);return;}if(step===1){setBusy(true);try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){Alert.alert(t('locationStep'),t('locationWhy'));return;}const fix=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});if(!fix.coords.accuracy||fix.coords.accuracy>100){Alert.alert(t('locationStep'),t('locationAccuracy'));return;}const proof=await mobileApi.verifyVisit(prototypeStoreId,{latitude:fix.coords.latitude,longitude:fix.coords.longitude,accuracy_meters:fix.coords.accuracy},locale);setProofId(proof.id);}catch{Alert.alert(t('locationStep'),t('visitVerificationFailed'));return;}finally{setBusy(false);}}if(step===3)await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.85});setStep(Math.min(step+1,4));};
  const publish=async()=>{if(!proofId||rating<1||text.trim().length<3)return;setBusy(true);try{await mobileApi.createReview({store_id:prototypeStoreId,text:text.trim(),rating,visit_verification_id:proofId,content_language:locale},locale);await mobileApi.clearVisitProof(prototypeStoreId);Alert.alert(t('createTitle'),t('published'));}catch{Alert.alert(t('createTitle'),t('publishFailed'));}finally{setBusy(false);}};
  return <ScrollView style={styles.screen} contentContainerStyle={styles.pad}><Text style={styles.kicker}>{t('create')}</Text><Text style={styles.title}>{t('createTitle')}</Text><View style={styles.steps}>{steps.map((s,i)=><View key={s} style={[styles.step,i===step&&styles.stepActive,i<step&&styles.stepDone]}><Text style={[styles.stepIndex,i===step&&{color:colors.surface}]}>{i<step?'✓':i+1}</Text><Text style={[styles.stepText,i===step&&{color:colors.surface}]}>{s}</Text></View>)}</View>{step===0&&<View style={styles.panel}><Text style={styles.panelTitle}>Luma Aydınlatma Kadıköy</Text><Text style={styles.meta}>Kadıköy, İstanbul</Text></View>}{step===1&&<Text style={styles.explainer}>{t('locationWhy')}</Text>}{step===2&&<View style={styles.ratingRow}>{[1,2,3,4,5].map(n=><Text onPress={()=>setRating(n)} key={n} style={[styles.star,n<=rating&&{color:colors.accent}]}>★</Text>)}</View>}{step===4&&<TextInput multiline value={text} onChangeText={setText} placeholder={t('experienceStep')} placeholderTextColor={colors.inkMuted} style={styles.textarea}/>}<PrimaryButton disabled={busy||(step===4&&(!proofId||rating<1||text.trim().length<3))} label={step===4?t('publish'):step===1?t('allowLocation'):steps[Math.min(step+1,4)]} onPress={step===4?()=>void publish():()=>void next()}/></ScrollView>;
}

export function FavoritesScreen({onAuth}:{onAuth:()=>void}) { const {t}=useI18n(); return <View style={[styles.screen,styles.pad]}><Text style={styles.kicker}>{t('favorites')}</Text><Text style={styles.title}>{t('favoritesTitle')}</Text><Text style={styles.explainer}>{t('favoritesEmpty')}</Text><PrimaryButton label={t('signInTitle')} onPress={onAuth}/></View> }
export function ProfileScreen({onAuth}:{onAuth:()=>void}) { const {t,locale,setLocale}=useI18n(); return <ScrollView style={styles.screen} contentContainerStyle={styles.pad}><Text style={styles.kicker}>{t('profile')}</Text><Text style={styles.title}>{t('profileTitle')}</Text><Text style={styles.explainer}>{t('profileBody')}</Text><PrimaryButton label={t('signInTitle')} onPress={onAuth}/><Text style={styles.sectionLabel}>{t('language')}</Text><View style={styles.languages}>{(Object.keys(localeNames) as Locale[]).map(l=><Text accessibilityRole="button" onPress={()=>setLocale(l)} key={l} style={[styles.language,l===locale&&styles.languageActive]}>{localeNames[l]}</Text>)}</View></ScrollView> }

const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas},pad:{padding:spacing.lg,paddingBottom:120},kicker:{fontSize:13,textTransform:'uppercase',letterSpacing:1.7,color:colors.accent,fontWeight:'800',marginTop:spacing.lg},title:{fontSize:34,lineHeight:40,fontWeight:'700',color:colors.ink,marginTop:spacing.md},steps:{marginTop:spacing.xxxl,gap:spacing.sm},step:{minHeight:52,backgroundColor:colors.muted,borderRadius:radius.control,paddingHorizontal:spacing.lg,flexDirection:'row',alignItems:'center',gap:spacing.md},stepActive:{backgroundColor:colors.ink},stepDone:{opacity:.6},stepIndex:{fontSize:13,fontWeight:'800',color:colors.ink},stepText:{fontSize:15,fontWeight:'600',color:colors.ink},panel:{padding:spacing.lg,backgroundColor:colors.surface,marginTop:spacing.xxl,borderRadius:radius.media},panelTitle:{fontSize:18,fontWeight:'700',color:colors.ink},meta:{fontSize:13,color:colors.inkMuted,marginTop:spacing.xs},explainer:{fontSize:16,lineHeight:24,color:colors.inkMuted,marginTop:spacing.xxl},ratingRow:{flexDirection:'row',justifyContent:'space-between',marginVertical:spacing.xxxl},star:{fontSize:42,color:colors.line},textarea:{minHeight:150,textAlignVertical:'top',padding:spacing.lg,borderWidth:1,borderColor:colors.line,borderRadius:radius.control,fontSize:16,color:colors.ink,marginTop:spacing.xxl,backgroundColor:colors.surface},sectionLabel:{fontSize:14,fontWeight:'700',color:colors.ink,marginTop:spacing.xxxl},languages:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm,marginTop:spacing.md},language:{paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderWidth:1,borderColor:colors.line,borderRadius:radius.pill,color:colors.ink},languageActive:{backgroundColor:colors.ink,color:colors.surface}});
