import React, { useState } from 'react';
import { Image, Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { Icon } from '../components/Icon';
import { PostCard } from '../components/PostCard';
import { Rating } from '../components/Primitives';
import { imagery, storeFixture } from '../data/fixtures';
import { useI18n } from '../i18n';
import { colors, fonts, radius, spacing } from '../theme/tokens';

export function StoreScreen({onBack,onAuth}:{onBack:()=>void;onAuth:()=>void}) { const {t,locale}=useI18n(); const {store}=storeFixture; const [saved,setSaved]=useState(store.viewer_has_favorited); const km=((store.distance_meters??0)/1000).toLocaleString(locale,{maximumFractionDigits:1}); const action=(name:string,label:string,onPress:()=>void)=><Pressable onPress={onPress} style={styles.action}><Icon name={name}/><Text style={styles.actionText}>{label}</Text></Pressable>;
 return <ScrollView style={styles.screen} contentContainerStyle={{paddingBottom:120}}><View><Image source={imagery.store} style={styles.hero}/><Pressable onPress={onBack} accessibilityLabel={t('back')} style={[styles.float,{left:spacing.lg}]}><Icon name="back" size={28}/></Pressable></View><View style={styles.content}><Text style={styles.kicker}>{store.category_labels.join(' · ')}</Text><Text style={styles.title}>{store.name}</Text><Text style={styles.place}>{store.district}, {store.city} · {km} km {t('away')}</Text><Text style={styles.question}>{t('storeQuestion')}</Text><View style={styles.metrics}><View><Text style={styles.metricLabel}>{t('communityRating')}</Text><View style={styles.bigScore}><Rating value={store.platform.average_rating} size="large"/><Text style={styles.metricMeta}>{store.platform.review_count} {t('reviews')}</Text></View></View><View style={styles.divider}/><View><Text style={styles.metricValue}>{store.platform.favorite_count}</Text><Text style={styles.metricLabel}>{t('favorites')}</Text></View></View><View style={styles.actions}>{action('bookmark',saved?t('saved'):t('save'),()=>{onAuth();setSaved(!saved)})}{action('directions',t('directions'),()=>{})}{action('create',t('review'),onAuth)}{action('share',t('share'),()=>Share.share({message:store.name}))}</View></View><View style={styles.gallery}><Image source={imagery.lighting} style={styles.galleryTall}/><Image source={imagery.feed} style={styles.gallerySmall}/></View><View style={styles.section}><Text style={styles.sectionTitle}>{t('about')}</Text><Text style={styles.description}>{store.localized_description}</Text><Text style={styles.address}>{store.address}, {store.district}/{store.city}</Text></View><View style={styles.section}><Text style={styles.sectionTitle}>{t('community')}</Text>{storeFixture.recent_posts.length?<PostCard post={storeFixture.recent_posts[0]} onProtected={onAuth} onStore={()=>{}}/>:<Text style={styles.description}>{t('noCommunity')}</Text>}</View><View style={styles.external}><Text style={styles.metricLabel}>{t('external')}</Text><Text style={styles.externalName}>Google Maps</Text><Text style={styles.description}>{t('externalSeparation')}</Text></View></ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas},hero:{width:'100%',aspectRatio:4/3,resizeMode:'cover'},float:{position:'absolute',top:spacing.lg,width:44,height:44,borderRadius:22,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},content:{padding:spacing.lg},kicker:{fontSize:12,textTransform:'uppercase',letterSpacing:1.2,fontFamily:fonts.bold,color:colors.clay},title:{fontFamily:fonts.bold,fontSize:32,lineHeight:38,color:colors.ink,marginTop:spacing.sm},place:{fontFamily:fonts.body,fontSize:14,color:colors.inkMuted,marginTop:spacing.sm},question:{fontSize:14,fontFamily:fonts.bold,color:colors.ink,marginTop:spacing.xxl},metrics:{flexDirection:'row',alignItems:'center',gap:spacing.xl,marginTop:spacing.md},metricLabel:{fontSize:11,textTransform:'uppercase',letterSpacing:.7,color:colors.inkMuted,fontFamily:fonts.bold},bigScore:{flexDirection:'row',alignItems:'baseline',gap:spacing.sm,marginTop:spacing.xs},metricMeta:{fontFamily:fonts.body,fontSize:13,color:colors.inkMuted},metricValue:{fontSize:22,fontFamily:fonts.bold,color:colors.ink},divider:{width:1,height:38,backgroundColor:colors.line},actions:{flexDirection:'row',justifyContent:'space-between',marginTop:spacing.xxl,paddingTop:spacing.lg,borderTopWidth:1,borderColor:colors.line},action:{alignItems:'center',justifyContent:'center',minWidth:68,minHeight:56,gap:spacing.xs},actionText:{fontFamily:fonts.medium,fontSize:12,color:colors.ink},gallery:{height:250,flexDirection:'row',gap:4,marginTop:spacing.sm},galleryTall:{flex:1,resizeMode:'cover'},gallerySmall:{width:'36%',resizeMode:'cover'},section:{paddingHorizontal:spacing.lg,paddingVertical:spacing.xxxl,borderBottomWidth:1,borderColor:colors.line},sectionTitle:{fontFamily:fonts.semibold,fontSize:24,lineHeight:30,color:colors.ink},description:{fontFamily:fonts.body,fontSize:16,lineHeight:24,color:colors.inkMuted,marginTop:spacing.md},address:{fontFamily:fonts.body,fontSize:15,lineHeight:22,color:colors.ink,marginTop:spacing.lg},external:{margin:spacing.lg,padding:spacing.lg,backgroundColor:colors.muted,borderRadius:radius.media},externalName:{fontFamily:fonts.semibold,fontSize:18,color:colors.ink,marginTop:spacing.sm}});
