import React, { useState } from 'react';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { mobileApi, mobileMediaSource } from '../api/client';
import type { Post } from '../api/types';
import { useI18n } from '../i18n';
import { colors, fonts, radius, spacing } from '../theme/tokens';
import { Icon } from './Icon';
import { Rating, VerifiedBadge } from './Primitives';

export function PostCard({post,onProtected,onStore}:{post:Post;onProtected:()=>void;onStore:()=>void}) {
  const {t,locale}=useI18n(); const [liked,setLiked]=useState(post.viewer_has_liked); const [saved,setSaved]=useState(post.viewer_has_favorited_store);const [busy,setBusy]=useState<'like'|'save'|null>(null);
  const date=new Intl.DateTimeFormat(locale,{day:'numeric',month:'short'}).format(new Date(post.created_at));const media=post.media[0];
  const mutate=async(kind:'like'|'save')=>{setBusy(kind);try{if(kind==='like'){await mobileApi.like(post.id,locale,liked);setLiked(value=>!value);}else{await mobileApi.favorite(post.store_id,locale,saved);setSaved(value=>!value);}}catch(reason){const code=(reason as {error?:{code?:string}})?.error?.code;if(code==='AUTH_REQUIRED'||code==='INVALID_TOKEN'||code==='INVALID_REFRESH_TOKEN')onProtected();}finally{setBusy(null);}};
  return <View style={styles.card}><View style={styles.userRow}><View style={styles.avatar}><Text style={styles.avatarText}>{post.display_name.slice(0,1).toLocaleUpperCase(locale)}</Text></View><View style={{flex:1}}><Text style={styles.name}>{post.display_name}</Text><Text style={styles.handle}>@{post.username} · {date}</Text></View><Pressable disabled={busy==='save'} accessibilityRole="button" accessibilityLabel={saved?t('saved'):t('save')} onPress={()=>void mutate('save')} hitSlop={10}><Icon name="bookmark" color={saved?colors.clay:colors.ink}/></Pressable></View>
    <Pressable onPress={onStore}><View style={styles.storeLine}><Text numberOfLines={1} style={styles.store}>{post.store_name}</Text><Text style={styles.place}>{[post.store_district,post.store_city].filter(Boolean).join(', ')}</Text></View></Pressable>
    <View style={styles.mediaFrame}>{media?<Image source={mobileMediaSource(media.url)} style={styles.media} accessibilityLabel={post.store_name}/>:<View style={styles.mediaEmpty}><Text style={styles.mediaEmptyMark}>{post.store_name.trim().slice(0,1)}</Text><Text style={styles.mediaEmptyText}>{t('noPhoto')}</Text></View>}{post.media.length>1&&<View style={styles.mediaIndex}><Text style={styles.mediaIndexText}>1 / {post.media.length}</Text></View>}</View>
    <View style={styles.meta}><Rating value={post.rating}/><VerifiedBadge/></View>
    <Text style={styles.body}>{post.text}</Text>
    <View style={styles.actions}><Pressable disabled={busy==='like'} style={styles.action} onPress={()=>void mutate('like')} accessibilityLabel={t('likes')}><Icon name="heart" color={liked?colors.clay:colors.ink}/><Text style={styles.actionText}>{post.like_count+(liked&&!post.viewer_has_liked?1:!liked&&post.viewer_has_liked?-1:0)}</Text></Pressable><Pressable style={styles.action} onPress={onProtected}><Icon name="comment"/><Text style={styles.actionText}>{post.comment_count}</Text></Pressable><Pressable style={styles.action} onPress={()=>{}}><Icon name="share"/><Text style={styles.actionText}>{t('share')}</Text></Pressable></View>
  </View>;
}
const styles=StyleSheet.create({card:{paddingTop:spacing.xxl,paddingBottom:spacing.xxl,borderBottomWidth:1,borderBottomColor:colors.line},userRow:{flexDirection:'row',alignItems:'center',gap:spacing.md,paddingHorizontal:spacing.lg},avatar:{width:40,height:40,borderRadius:radius.pill,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center'},avatarText:{color:colors.white,fontSize:17,fontFamily:fonts.bold},name:{fontSize:14,fontFamily:fonts.bold,color:colors.ink},handle:{fontSize:12,fontFamily:fonts.body,color:colors.inkMuted,marginTop:2},storeLine:{paddingHorizontal:spacing.lg,marginTop:spacing.xl,marginBottom:spacing.md},store:{fontSize:22,lineHeight:27,fontFamily:fonts.semibold,color:colors.ink,letterSpacing:-.5},place:{fontSize:13,fontFamily:fonts.medium,color:colors.clay,marginTop:4},mediaEmpty:{flex:1,alignItems:'center',justifyContent:'center',gap:spacing.sm,backgroundColor:colors.muted},mediaEmptyMark:{fontFamily:fonts.bold,fontSize:44,color:colors.inkMuted,letterSpacing:-1.5},mediaEmptyText:{fontFamily:fonts.semibold,fontSize:12,letterSpacing:1,textTransform:'uppercase',color:colors.inkMuted},mediaFrame:{marginHorizontal:spacing.lg,aspectRatio:4/5,borderRadius:radius.media,overflow:'hidden',backgroundColor:colors.muted,position:'relative'},media:{width:'100%',height:'100%',resizeMode:'cover'},mediaIndex:{position:'absolute',right:10,top:10,backgroundColor:colors.ink,paddingHorizontal:9,paddingVertical:5,borderRadius:radius.pill},mediaIndexText:{fontSize:10,lineHeight:12,color:colors.surface,fontFamily:fonts.bold},meta:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginHorizontal:spacing.lg,marginTop:spacing.md,backgroundColor:'transparent'},body:{fontSize:17,lineHeight:27,fontFamily:fonts.body,color:colors.ink,marginHorizontal:spacing.lg,paddingTop:spacing.md},actions:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginHorizontal:spacing.lg,paddingTop:spacing.sm},action:{minWidth:44,minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.sm},actionText:{fontSize:13,fontFamily:fonts.medium,color:colors.inkMuted}});
